sudo: required
language: python
cache: pip
python:
  - '3.5'
services:
  - docker
install:
  - docker-compose build
script: docker-compose run --service-ports eve_example make test
after_success:
  coveralls
